--
-- PostgreSQL database dump
--

\restrict 9hLnxHaWiSLaaqZ94N0qKht59JzMH5Ma1RusOq0VEJEpukvB8kn9HOLNzx19HGX

-- Dumped from database version 15.14
-- Dumped by pg_dump version 15.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: allergies; Type: TABLE; Schema: public; Owner: vitalmedic_user
--

CREATE TABLE public.allergies (
    id bigint NOT NULL,
    criticality character varying(255),
    fhir_id character varying(255),
    reaction character varying(255),
    reaction_description character varying(255),
    severity character varying(255),
    substance character varying(255),
    patient_id uuid
);


ALTER TABLE public.allergies OWNER TO vitalmedic_user;

--
-- Name: allergies_id_seq; Type: SEQUENCE; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE public.allergies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.allergies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments; Type: TABLE; Schema: public; Owner: vitalmedic_user
--

CREATE TABLE public.appointments (
    id bigint NOT NULL,
    end_at timestamp(6) without time zone,
    fhir_id character varying(255),
    reason character varying(255),
    room_id character varying(255),
    start_at timestamp(6) without time zone,
    status character varying(255),
    doctor_id uuid,
    patient_id uuid
);


ALTER TABLE public.appointments OWNER TO vitalmedic_user;

--
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE public.appointments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conditions; Type: TABLE; Schema: public; Owner: vitalmedic_user
--

CREATE TABLE public.conditions (
    id bigint NOT NULL,
    clinical_status character varying(255),
    code character varying(255),
    description character varying(255),
    fhir_id character varying(255),
    start_date timestamp(6) without time zone,
    patient_id uuid
);


ALTER TABLE public.conditions OWNER TO vitalmedic_user;

--
-- Name: conditions_id_seq; Type: SEQUENCE; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE public.conditions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conditions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctors; Type: TABLE; Schema: public; Owner: vitalmedic_user
--

CREATE TABLE public.doctors (
    id uuid NOT NULL,
    experience text,
    first_name character varying(100),
    last_name character varying(100),
    license_number character varying(50) NOT NULL,
    phone character varying(20),
    specialty character varying(100) NOT NULL
);


ALTER TABLE public.doctors OWNER TO vitalmedic_user;

--
-- Name: medications; Type: TABLE; Schema: public; Owner: vitalmedic_user
--

CREATE TABLE public.medications (
    id bigint NOT NULL,
    dosage character varying(255),
    effective_date timestamp(6) without time zone,
    fhir_id character varying(255),
    medication_name character varying(255),
    status character varying(255),
    patient_id uuid
);


ALTER TABLE public.medications OWNER TO vitalmedic_user;

--
-- Name: medications_id_seq; Type: SEQUENCE; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE public.medications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: observations; Type: TABLE; Schema: public; Owner: vitalmedic_user
--

CREATE TABLE public.observations (
    id bigint NOT NULL,
    code character varying(255),
    date timestamp(6) without time zone,
    fhir_id character varying(255),
    unit character varying(255),
    value character varying(255),
    patient_id uuid
);


ALTER TABLE public.observations OWNER TO vitalmedic_user;

--
-- Name: observations_id_seq; Type: SEQUENCE; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE public.observations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.observations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patient_identifiers; Type: TABLE; Schema: public; Owner: vitalmedic_user
--

CREATE TABLE public.patient_identifiers (
    id bigint NOT NULL,
    system character varying(255) NOT NULL,
    value character varying(255) NOT NULL,
    patient_id uuid,
    CONSTRAINT patient_identifiers_system_check CHECK (((system)::text = ANY ((ARRAY['CURP'::character varying, 'RFC'::character varying, 'NSS_IMSS'::character varying, 'ISSSTE'::character varying, 'PRIVATE_INSURANCE'::character varying, 'VITALMEDIC_INTERNAL'::character varying])::text[])))
);


ALTER TABLE public.patient_identifiers OWNER TO vitalmedic_user;

--
-- Name: patient_identifiers_id_seq; Type: SEQUENCE; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE public.patient_identifiers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patient_identifiers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients; Type: TABLE; Schema: public; Owner: vitalmedic_user
--

CREATE TABLE public.patients (
    id uuid NOT NULL,
    address character varying(255),
    birth_date date,
    fhir_id character varying(255),
    first_name character varying(100),
    gender character varying(255),
    imported_from_fhir boolean,
    last_name character varying(100),
    onboarding_status character varying(255),
    phone character varying(20),
    CONSTRAINT patients_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT patients_onboarding_status_check CHECK (((onboarding_status)::text = ANY ((ARRAY['PENDING_IDENTIFIER'::character varying, 'IMPORT_PROMPT'::character varying, 'MANUAL_ENTRY'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.patients OWNER TO vitalmedic_user;

--
-- Name: users; Type: TABLE; Schema: public; Owner: vitalmedic_user
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(100) NOT NULL,
    keycloak_id uuid,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(100) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['PATIENT'::character varying, 'DOCTOR'::character varying, 'ADMIN'::character varying, 'ONBOARDING_PENDING'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO vitalmedic_user;

--
-- Name: allergies allergies_pkey; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.allergies
    ADD CONSTRAINT allergies_pkey PRIMARY KEY (id);


--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);


--
-- Name: conditions conditions_pkey; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.conditions
    ADD CONSTRAINT conditions_pkey PRIMARY KEY (id);


--
-- Name: doctors doctors_pkey; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_pkey PRIMARY KEY (id);


--
-- Name: medications medications_pkey; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.medications
    ADD CONSTRAINT medications_pkey PRIMARY KEY (id);


--
-- Name: observations observations_pkey; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT observations_pkey PRIMARY KEY (id);


--
-- Name: patient_identifiers patient_identifiers_pkey; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.patient_identifiers
    ADD CONSTRAINT patient_identifiers_pkey PRIMARY KEY (id);


--
-- Name: patients patients_pkey; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_pkey PRIMARY KEY (id);


--
-- Name: users uk366dgrd625s5659shyen79mmw; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk366dgrd625s5659shyen79mmw UNIQUE (keycloak_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: patient_identifiers ukh36yfdfuq6wds0iw5c3fx6ic9; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.patient_identifiers
    ADD CONSTRAINT ukh36yfdfuq6wds0iw5c3fx6ic9 UNIQUE (value);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_appointments_doctor_id; Type: INDEX; Schema: public; Owner: vitalmedic_user
--

CREATE INDEX idx_appointments_doctor_id ON public.appointments USING btree (doctor_id);


--
-- Name: idx_appointments_patient_id; Type: INDEX; Schema: public; Owner: vitalmedic_user
--

CREATE INDEX idx_appointments_patient_id ON public.appointments USING btree (patient_id);


--
-- Name: idx_appointments_start_at; Type: INDEX; Schema: public; Owner: vitalmedic_user
--

CREATE INDEX idx_appointments_start_at ON public.appointments USING btree (start_at);


--
-- Name: idx_appointments_status; Type: INDEX; Schema: public; Owner: vitalmedic_user
--

CREATE INDEX idx_appointments_status ON public.appointments USING btree (status);


--
-- Name: conditions fk6sofvin9w20fcph1764kmiauc; Type: FK CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.conditions
    ADD CONSTRAINT fk6sofvin9w20fcph1764kmiauc FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: patient_identifiers fk87bs7e28dxevpavij7kca8uv4; Type: FK CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.patient_identifiers
    ADD CONSTRAINT fk87bs7e28dxevpavij7kca8uv4 FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: appointments fk8exap5wmg8kmb1g1rx3by21yt; Type: FK CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk8exap5wmg8kmb1g1rx3by21yt FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: medications fkc2gnonyv0fynih7tkrre0m46x; Type: FK CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.medications
    ADD CONSTRAINT fkc2gnonyv0fynih7tkrre0m46x FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: doctors fkgisys6qm9qflq8w4npdhxafne; Type: FK CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT fkgisys6qm9qflq8w4npdhxafne FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: observations fkia1iwfhjo4gdq1dwy7vqjr31x; Type: FK CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.observations
    ADD CONSTRAINT fkia1iwfhjo4gdq1dwy7vqjr31x FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: allergies fkjnxfgm2wbbwrx9639ay1or4o; Type: FK CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.allergies
    ADD CONSTRAINT fkjnxfgm2wbbwrx9639ay1or4o FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: appointments fkmujeo4tymoo98cmf7uj3vsv76; Type: FK CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fkmujeo4tymoo98cmf7uj3vsv76 FOREIGN KEY (doctor_id) REFERENCES public.doctors(id);


--
-- Name: patients fkn8xphvlp05nd3ydg0p1rbdaom; Type: FK CONSTRAINT; Schema: public; Owner: vitalmedic_user
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT fkn8xphvlp05nd3ydg0p1rbdaom FOREIGN KEY (id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 9hLnxHaWiSLaaqZ94N0qKht59JzMH5Ma1RusOq0VEJEpukvB8kn9HOLNzx19HGX

